#!/bin/bash


clingoPath=""
if [ -f ./clingo ];
     then
clingoPath="./clingo" ;
elif [ -f ./clingo.bin ];
     then
clingoPath="./clingo.bin" ;
elif [ -f ./clingo.exe ];
     then
clingoPath="./clingo.exe" ;

elif which clingo &> /dev/null ;
     then
clingoPath="clingo" ;
else
echo "ERROR: clingo was not found" ;
      exit
fi

last_sparc_arg=1;

if [ "$2" = "--warnings" ];
  then
  last_sparc_arg=$last_sparc_arg+1;
fi

declare file="$1"
declare regex=":+"


declare file_content=$( cat "${file}" )
if [[ " $file_content " =~ $regex ]] 
    then
        echo "error: input program contains a consistency restoring rule"
fi
exit

echo $clingoPath

java -jar sparc.jar "${@:1:$last_sparc_arg}" | $clingoPath ${*:last_sparc_arg+1} 2>&1


