/* Generated By:JJTree: Do not edit this line. QASTsymbolicFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=QAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package querying.parsing.query;

public
class QASTsymbolicFunction extends SimpleNode {
  public QASTsymbolicFunction(int id) {
    super(id);
  }

  public QASTsymbolicFunction(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aef56c90b2b9fade940cb14d8c867d45 (do not edit this line) */
