/* Generated By:JJTree: Do not edit this line. QASTtermList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=QAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package querying.parsing.query;

public
class QASTtermList extends SimpleNode {
  public QASTtermList(int id) {
    super(id);
  }

  public QASTtermList(QueryParser p, int id) {
    super(p, id);
  }
  
  public String toString() {
	  StringBuilder result=new StringBuilder();
	  for(int i=0;i<this.jjtGetNumChildren();i++) {
		  if(i!=0)
			  result.append(",");
		  result.append(((SimpleNode)this.jjtGetChild(i)).toString());
	  }
	  return result.toString();
  }

}
/* JavaCC - OriginalChecksum=c5b100d59bc8e9ffca8432d1f1f76673 (do not edit this line) */
