/* Generated By:JJTree: Do not edit this line. ASTatomSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTatomSequence extends SimpleNode {
  public ASTatomSequence(int id) {
    super(id);
  }

  public ASTatomSequence(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6349fff36ee1b332318384e76fbdb66a (do not edit this line) */
