/* Generated By:JJTree: Do not edit this line. ASTatom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTatom extends SimpleNode {
  public ASTatom(int id) {
    super(id);
  }

  public ASTatom(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	   /*
	   aggregate()|+
	   symbolicTerm()  rel()  symbolicTerm() |
	   symbolicTerm() rel() var()|
	   arithmeticTerm()  rel()  arithmeticTerm()|
	   var()  rel() symbolicTerm() |
	   arithmeticTerm()  eqrel()  symbolicTerm() |
	   symbolicTerm()  eqrel()  arithmeticTerm()| 
	   extendedNonRelAtom() +
	   var() eq var()
	   */ 
	  if(this.jjtGetNumChildren()>0 && (((SimpleNode)(this.jjtGetChild(0))).getId()
			  ==SparcTranslatorTreeConstants.JJTAGGREGATE||
			  (((SimpleNode)(this.jjtGetChild(0))).getId()
					  ==SparcTranslatorTreeConstants.JJTEXTENDEDNONRELATOM))) {
		  return ((SimpleNode)(this.jjtGetChild(0))).toString();
	  }
	  else if(this.jjtGetNumChildren()==2) {
		  SimpleNode child1=(SimpleNode)this.jjtGetChild(0);
		  SimpleNode child2=(SimpleNode)this.jjtGetChild(1);
		  return child1.toString()+this.image+child2.toString();
	  }
	  else {
		  return this.image;
	  }
	   
  }
}
/* JavaCC - OriginalChecksum=68be2106f288cf287b9a442791f7190c (do not edit this line) */
