/* Generated By:JJTree: Do not edit this line. ASTadditiveSetExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTadditiveSetExpression extends SimpleNode {
  public ASTadditiveSetExpression(int id) {
    super(id);
  }

  public ASTadditiveSetExpression(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a4d4a33bbd6e5cf007cc1a144a761ed6 (do not edit this line) */
