/* Generated By:JJTree: Do not edit this line. ASTadditiveSortExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTadditiveSortExpression extends SimpleNode {
  public ASTadditiveSortExpression(int id) {
    super(id);
  }

  public ASTadditiveSortExpression(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c3352033a15deeede93e70baa73029c (do not edit this line) */
