/* Generated By:JJTree: Do not edit this line. ASTandCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTandCondition extends SimpleNode {
  public ASTandCondition(int id) {
    super(id);
  }

  public ASTandCondition(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8f7ec778b6eacd45440f26d65b5bc3a (do not edit this line) */
