/* Generated By:JJTree: Do not edit this line. ASTbasicSort.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTbasicSort extends SimpleNode {
  public ASTbasicSort(int id) {
    super(id);
  }

  public ASTbasicSort(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c011a32bd15df47e62466f2336055b89 (do not edit this line) */
