/* Generated By:JJTree: Do not edit this line. ASTcomplexRegularExpressionChoices.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTcomplexRegularExpressionChoices extends SimpleNode {
  public ASTcomplexRegularExpressionChoices(int id) {
    super(id);
  }

  public ASTcomplexRegularExpressionChoices(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88076269034361b24707555aa86167b2 (do not edit this line) */
