/* Generated By:JJTree: Do not edit this line. ASTchoice_rule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTchoice_rule extends SimpleNode {
  public ASTchoice_rule(int id) {
    super(id);
  }

  public ASTchoice_rule(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
}
/* JavaCC - OriginalChecksum=96e827c9aa11c383a197dc09d1b4873e (do not edit this line) */
