/* Generated By:JJTree: Do not edit this line. ASTconstraintParams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTconstraintParams extends SimpleNode {
  public ASTconstraintParams(int id) {
    super(id);
  }

  public ASTconstraintParams(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  StringBuilder res=new StringBuilder();
	  res.append("[");
	  int colIndex=this.image.indexOf(':');
      if(this.image.startsWith("V")) {
    	  ASTvar var1=(ASTvar)this.jjtGetChild(0);
    	  res.append(var1.toString());
      }
      else res.append(this.image.substring(0,colIndex));
      res.append(":");
      if(this.image.endsWith("V")) {
    	  ASTvar var2=(ASTvar)this.jjtGetChild(this.jjtGetNumChildren()-1);
    	  res.append(var2.toString());
      }
      else res.append(this.image.substring(colIndex+1)); 
	  res.append("]");
	  return res.toString();
  }
}
/* JavaCC - OriginalChecksum=a999d85ec1315e194b39a7caf2f54d2e (do not edit this line) */
