/* Generated By:JJTree: Do not edit this line. ASTidentifierRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTidentifierRange extends SimpleNode {
  public ASTidentifierRange(int id) {
    super(id);
  }

  public ASTidentifierRange(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f038884bfe545683808918a073c0e363 (do not edit this line) */
