/* Generated By:JJTree: Do not edit this line. ASTunaryCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import java.util.HashMap;

public class ASTunaryCondition extends SimpleNode {
	public ASTunaryCondition(int id) {
		super(id);
	}

	public ASTunaryCondition(SparcTranslator p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	//public String toString(HashMap<String, Integer> map) throws ParseException {
	//	ASTvar child1 = ((ASTvar) (this.jjtGetChild(0)));
	//	ASTvar child2 = ((ASTvar) (this.jjtGetChild(1)));
		
	//	return "{" + map.get(child1.toString()) + this.image + map.get(child2.toString()) + "}";
	//}

	public String toString() {
		return image;
	}
}
/*
 * JavaCC - OriginalChecksum=77fb562736f9dd899a7e18d5d0c07eb7 (do not edit this
 * line)
 */
