/* Generated By:JavaCC: Do not edit this line. SparcTranslatorTreeConstants.java Version 5.0 */
package parser;

public interface SparcTranslatorTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSORTDEFINITIONS = 1;
  public int JJTSORTDEFINITION = 2;
  public int JJTSORTEXPRESSION = 3;
  public int JJTSETEXPRESSION = 4;
  public int JJTMULTIPLICATIVESETEXPRESSION = 5;
  public int JJTADDITIVESETEXPRESSION = 6;
  public int JJTSORTNAME = 7;
  public int JJTUNARYSETEXPRESSION = 8;
  public int JJTCURLYBRACKETS = 9;
  public int JJTCONSTANTTERMLIST = 10;
  public int JJTCONSTANTTERM = 11;
  public int JJTCONDITION = 12;
  public int JJTORCONDITION = 13;
  public int JJTANDCONDITION = 14;
  public int JJTUNARYCONDITION = 15;
  public int JJTFUNCTIONALSYMBOL = 16;
  public int JJTVOID = 17;
  public int JJTSORTEXPRESSIONLIST = 18;
  public int JJTCONCATENATION = 19;
  public int JJTBASICSORT = 20;
  public int JJTIDENTIFIERRANGE = 21;
  public int JJTNUMERICRANGE = 22;
  public int JJTPREDICATEDECLARATIONS = 23;
  public int JJTPREDICATEDECLARATION = 24;
  public int JJTIDENTIFIERLIST = 25;
  public int JJTPROGRAMRULES = 26;
  public int JJTPROGRAMRULE = 27;
  public int JJTUNLABELEDPROGRAMRULE = 28;
  public int JJTCONSTRAINTPARAMS = 29;
  public int JJTUNLABELEDPROGRAMCRRULE = 30;
  public int JJTHEAD = 31;
  public int JJTDISJUNCTION = 32;
  public int JJTCHOICE_RULE = 33;
  public int JJTCHOICE_ELEMENTS = 34;
  public int JJTCHOICE_ELEMENT = 35;
  public int JJTEXTENDEDSIMPLEATOMLIST = 36;
  public int JJTBODY = 37;
  public int JJTVAR = 38;
  public int JJTNONRELATOM = 39;
  public int JJTSIMPLEATOM = 40;
  public int JJTEXTENDEDNONRELATOM = 41;
  public int JJTARITHMETICTERM = 42;
  public int JJTATOMICARITHMETICTERM = 43;
  public int JJTADDITIVEARITHMETICTERM = 44;
  public int JJTMULTIPLICATIVEARITHMETICTERM = 45;
  public int JJTSYMBOLICFUNCTION = 46;
  public int JJTSYMBOLICCONSTANT = 47;
  public int JJTSYMBOLICTERM = 48;
  public int JJTTERM = 49;
  public int JJTTERMLIST = 50;
  public int JJTPREDSYMBOL = 51;
  public int JJTATOM = 52;
  public int JJTAGGREGATE = 53;
  public int JJTAGGREGATEELEMENTS = 54;
  public int JJTAGGREGATEELEMENT = 55;
  public int JJTAGGREGATEFUNCTION = 56;
  public int JJTATOMSEQUENCE = 57;
  public int JJTCHARACTERREGULAREXPRESSION = 58;


  public String[] jjtNodeName = {
    "program",
    "sortDefinitions",
    "sortDefinition",
    "sortExpression",
    "setExpression",
    "multiplicativeSetExpression",
    "additiveSetExpression",
    "sortName",
    "unarySetExpression",
    "curlyBrackets",
    "constantTermList",
    "constantTerm",
    "condition",
    "orCondition",
    "andCondition",
    "unaryCondition",
    "functionalSymbol",
    "void",
    "sortExpressionList",
    "concatenation",
    "basicSort",
    "identifierRange",
    "numericRange",
    "predicateDeclarations",
    "predicateDeclaration",
    "identifierList",
    "programRules",
    "programRule",
    "unlabeledProgramRule",
    "constraintParams",
    "unlabeledProgramCrRule",
    "head",
    "disjunction",
    "choice_rule",
    "choice_elements",
    "choice_element",
    "extendedSimpleAtomList",
    "body",
    "var",
    "nonRelAtom",
    "simpleAtom",
    "extendedNonRelAtom",
    "arithmeticTerm",
    "atomicArithmeticTerm",
    "additiveArithmeticTerm",
    "multiplicativeArithmeticTerm",
    "symbolicFunction",
    "symbolicConstant",
    "symbolicTerm",
    "term",
    "termList",
    "predSymbol",
    "atom",
    "aggregate",
    "aggregateElements",
    "aggregateElement",
    "aggregateFunction",
    "atomSequence",
    "characterRegularExpression",
  };
}
/* JavaCC - OriginalChecksum=7ad2fc6b9869c4f1c6d406bec82bf423 (do not edit this line) */
