/* Generated By:JJTree&JavaCC: Do not edit this line. SparcTranslatorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SparcTranslatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAXINTDIRECTIVE = 1;
  /** RegularExpression Id. */
  int CONSTDIRECTIVE = 2;
  /** RegularExpression Id. */
  int SORTDEFKEYWORD = 3;
  /** RegularExpression Id. */
  int PREDDEFKEYWORD = 4;
  /** RegularExpression Id. */
  int PROGRULDEFKEYWORD = 5;
  /** RegularExpression Id. */
  int NOT = 6;
  /** RegularExpression Id. */
  int NOTOP = 7;
  /** RegularExpression Id. */
  int MOD = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int NONZERODIGIT = 13;
  /** RegularExpression Id. */
  int POSITIVE_INTEGER = 14;
  /** RegularExpression Id. */
  int ZERO = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MULT = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int EQR = 20;
  /** RegularExpression Id. */
  int NOTEQ = 21;
  /** RegularExpression Id. */
  int GT = 22;
  /** RegularExpression Id. */
  int GTEQ = 23;
  /** RegularExpression Id. */
  int SM = 24;
  /** RegularExpression Id. */
  int SMEQ = 25;
  /** RegularExpression Id. */
  int OP = 26;
  /** RegularExpression Id. */
  int CP = 27;
  /** RegularExpression Id. */
  int OB = 28;
  /** RegularExpression Id. */
  int CB = 29;
  /** RegularExpression Id. */
  int ORRSEP = 30;
  /** RegularExpression Id. */
  int CRRSEP = 31;
  /** RegularExpression Id. */
  int WEAKSEP = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int COLON = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int DOLLAR = 37;
  /** RegularExpression Id. */
  int COMPLEMENT = 38;
  /** RegularExpression Id. */
  int HEAD_OR = 39;
  /** RegularExpression Id. */
  int AGGREGATE_COUNT = 40;
  /** RegularExpression Id. */
  int AGGREGATE_SUM = 41;
  /** RegularExpression Id. */
  int AGGREGATE_MIN = 42;
  /** RegularExpression Id. */
  int AGGREGATE_MAX = 43;
  /** RegularExpression Id. */
  int OSB = 44;
  /** RegularExpression Id. */
  int OCB = 45;
  /** RegularExpression Id. */
  int POUND_SIGN = 46;
  /** RegularExpression Id. */
  int IDENTIFIER_WITH_OP = 47;
  /** RegularExpression Id. */
  int NEGATIVE_ATOM_WITH_OP = 48;
  /** RegularExpression Id. */
  int NEGATIVE_SORT_ATOM_WITH_OP = 49;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 50;
  /** RegularExpression Id. */
  int SPACE = 51;
  /** RegularExpression Id. */
  int MINUS = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_PROGRAM_RULES = 1;
  /** Lexical state. */
  int IN_REGULAREXPRESSIONSEQUENCE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"#maxint\"",
    "\"#const\"",
    "<SORTDEFKEYWORD>",
    "<PREDDEFKEYWORD>",
    "<PROGRULDEFKEYWORD>",
    "<NOT>",
    "<NOTOP>",
    "\"mod\"",
    "\"or\"",
    "\"and\"",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<NONZERODIGIT>",
    "<POSITIVE_INTEGER>",
    "\"0\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":-\"",
    "\":+\"",
    "\":~\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"$\"",
    "\"~\"",
    "\"|\"",
    "\"#count\"",
    "\"#sum\"",
    "\"#min\"",
    "\"#max\"",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "<IDENTIFIER_WITH_OP>",
    "<NEGATIVE_ATOM_WITH_OP>",
    "<NEGATIVE_SORT_ATOM_WITH_OP>",
    "<SINGLE_LINE_COMMENT>",
    "<SPACE>",
    "\"-\"",
  };

}
