/* Generated By:JJTree: Do not edit this line. ASTaggregateFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTaggregateFunction extends SimpleNode {
  public ASTaggregateFunction(int id) {
    super(id);
  }

  public ASTaggregateFunction(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  return this.image;
  }
}
/* JavaCC - OriginalChecksum=fc758f706928c27e1d80f2cb2425868b (do not edit this line) */
