/* Generated By:JJTree: Do not edit this line. ASTcomplexRegularExpressionUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTcomplexRegularExpressionUnit extends SimpleNode {
  public ASTcomplexRegularExpressionUnit(int id) {
    super(id);
  }

  public ASTcomplexRegularExpressionUnit(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7d1865f26cd6bfa5fe294ab097b2701e (do not edit this line) */
