/* Generated By:JJTree: Do not edit this line. ASTconcatenation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTconcatenation extends SimpleNode {
  public ASTconcatenation(int id) {
    super(id);
  }

  public ASTconcatenation(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=173e0fb7b15fa6c516dfeced049b6317 (do not edit this line) */
