/* Generated By:JJTree: Do not edit this line. ASTchoice_elements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTchoice_elements extends SimpleNode {
  public ASTchoice_elements(int id) {
    super(id);
  }

  public ASTchoice_elements(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fdc1fa5444a9da4c953de12903438524 (do not edit this line) */
