/* Generated By:JJTree: Do not edit this line. ASTextendedNonRelAtom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import java.util.HashMap;

public class ASTextendedNonRelAtom extends SimpleNode {
	public ASTextendedNonRelAtom(int id) {
		super(id);
	}

	public ASTextendedNonRelAtom(SparcTranslator p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	 
	  // disallow toString() call without sort renaming map
	  @Override
	  public String toString() {
		  throw new UnsupportedOperationException();
	  }
	  

	public String toString(HashMap<String,String> sortRenaming) {
		StringBuilder sb = new StringBuilder();
		if (!this.image.equals("")) {
			sb.append(this.image + " ");
		}
		// predSymbol
		sb.append(((ASTpredSymbol) this.jjtGetChild(0)).toString(sortRenaming));
		if (this.jjtGetNumChildren() > 1) {
			sb.append("(");
			// termList
			sb.append(((SimpleNode) this.jjtGetChild(1)).toString());
			sb.append(")");
		}
		return sb.toString();
	}
}
/*
 * JavaCC - OriginalChecksum=15b497e35e55136f9fe9eba7e2b8fe79 (do not edit this
 * line)
 */
