/* Generated By:JJTree: Do not edit this line. ASTextendedSimpleAtomList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTextendedSimpleAtomList extends SimpleNode {
  public ASTextendedSimpleAtomList(int id) {
    super(id);
  }

  public ASTextendedSimpleAtomList(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  StringBuilder result=new StringBuilder();
	  for(int i=0;i<this.jjtGetNumChildren();i++) {
		  ASTsimpleAtom atom=(ASTsimpleAtom)this.jjtGetChild(i);
		  if(i!=0) {
			  result.append(',');
		  }
		  result.append(atom.toString());
	  }
	  return result.toString();  
  }
}
/* JavaCC - OriginalChecksum=f561dc19d13af200b566d1577ef30d26 (do not edit this line) */
