/* Generated By:JJTree: Do not edit this line. ASTidentifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTidentifierList extends SimpleNode {
  public ASTidentifierList(int id) {
    super(id);
  }

  public ASTidentifierList(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75d8dab5f63986637c20723bad1675a3 (do not edit this line) */
