/* Generated By:JJTree: Do not edit this line. ASTmultiplicativeSetExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTmultiplicativeSetExpression extends SimpleNode {
  public ASTmultiplicativeSetExpression(int id) {
    super(id);
  }

  public ASTmultiplicativeSetExpression(SparcTranslator p, int id) {
    super(p, id);
  }

  public String toString() {
	 return ((ASTunarySetExpression)this.jjtGetChild(0)).toString();
  }
}
/* JavaCC - OriginalChecksum=bc4548a9bfeadf2b969d87fc4b66ee8e (do not edit this line) */
