/* Generated By:JJTree: Do not edit this line. ASTmultiplicativeSortExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTmultiplicativeSortExpression extends SimpleNode {
  public ASTmultiplicativeSortExpression(int id) {
    super(id);
  }

  public ASTmultiplicativeSortExpression(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0b3e428d083b03087e5c45cbaac3dfc6 (do not edit this line) */
