/* Generated By:JJTree: Do not edit this line. ASTnumericRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTnumericRange extends SimpleNode {
  public ASTnumericRange(int id) {
    super(id);
  }

  public ASTnumericRange(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=abf2aae97a0b7818790ae219d682a864 (do not edit this line) */
