/* Generated By:JJTree: Do not edit this line. ASToptimizeParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import java.util.HashMap;

public
class ASToptimizeParameter extends SimpleNode {
  public ASToptimizeParameter(int id) {
    super(id);
  }

  public ASToptimizeParameter(SparcTranslator p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString(HashMap<String,String> sortRenaming) {
    StringBuilder result=new StringBuilder();
    result.append(this.image);
    return result.toString();	  
  }
}

/* JavaCC - OriginalChecksum=cef9691d64a38012952b9a7f8e59ef2b (do not edit this line) */
