/* Generated By:JJTree: Do not edit this line. ASTorCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTorCondition extends SimpleNode {
  public ASTorCondition(int id) {
    super(id);
  }

  public ASTorCondition(SparcTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d10e0028651dd41bd286ae730919bf03 (do not edit this line) */
