/* Generated By:JJTree: Do not edit this line. ASTregularExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTregularExpression extends SimpleNode {
  public ASTregularExpression(int id) {
    super(id);
  }

  public ASTregularExpression(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d10df7d48c8a5bf449cd2ded8aeed824 (do not edit this line) */
