/* Generated By:JJTree: Do not edit this line. ASTsortDefinitions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTsortDefinitions extends SimpleNode {
  public ASTsortDefinitions(int id) {
    super(id);
  }

  public ASTsortDefinitions(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5982e8056d2e0617f8ec609f6a773e39 (do not edit this line) */
