/* Generated By:JJTree: Do not edit this line. ASTsortName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTsortName extends SimpleNode {
  public ASTsortName(int id) {
    super(id);
  }

  public ASTsortName(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  return this.image;
  }
}
/* JavaCC - OriginalChecksum=4c52322693db3f097149b83a40202d19 (do not edit this line) */
