/* Generated By:JJTree: Do not edit this line. ASTsymbolicConstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTsymbolicConstant extends SimpleNode {
  public ASTsymbolicConstant(int id) {
    super(id);
  }

  public ASTsymbolicConstant(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  return this.image;
  }
}
/* JavaCC - OriginalChecksum=6529067edf29eb5505fafa4ccf20cab0 (do not edit this line) */
