/* Generated By:JJTree: Do not edit this line. ASTsymbolicFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTsymbolicFunction extends SimpleNode {
  public ASTsymbolicFunction(int id) {
    super(id);
  }

  public ASTsymbolicFunction(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  return this.image;
  }
}
/* JavaCC - OriginalChecksum=a0e849a6824cddc63ede9c8d40dbab7d (do not edit this line) */
