/* Generated By:JJTree: Do not edit this line. ASTunarySortExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTunarySortExpression extends SimpleNode {
  public ASTunarySortExpression(int id) {
    super(id);
  }

  public ASTunarySortExpression(SparcTranslator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SparcTranslatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fed6127294f2f14c81a4f5e960279f2a (do not edit this line) */
