/* Generated By:JavaCC: Do not edit this line. SparcTranslatorVisitor.java Version 5.0 */
package parser;

public interface SparcTranslatorVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTsortDefinitions node, Object data);
  public Object visit(ASTsortDefinition node, Object data);
  public Object visit(ASTsortExpression node, Object data);
  public Object visit(ASTadditiveSortExpression node, Object data);
  public Object visit(ASTmultiplicativeSortExpression node, Object data);
  public Object visit(ASTregularExpression node, Object data);
  public Object visit(ASTcomplexRegularExpressionChoices node, Object data);
  public Object visit(ASTcomplexRegularExpression node, Object data);
  public Object visit(ASTcomplexRegularExpressionRepeatableUnit node, Object data);
  public Object visit(ASTcomplexRegularExpressionUnit node, Object data);
  public Object visit(ASTcomplexRegularExpressionUnitIdentifier node, Object data);
  public Object visit(ASTrepeatition node, Object data);
  public Object visit(ASTcharacterList node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTunarySortExpression node, Object data);
  public Object visit(ASTsortExpressionList node, Object data);
  public Object visit(ASTpredicateDeclarations node, Object data);
  public Object visit(ASTpredicateDeclaration node, Object data);
  public Object visit(ASTidentifierList node, Object data);
  public Object visit(ASTprogramRules node, Object data);
  public Object visit(ASTprogramRule node, Object data);
  public Object visit(ASTunlabeledProgramRule node, Object data);
  public Object visit(ASTconstraintParams node, Object data);
  public Object visit(ASTunlabeledProgramCrRule node, Object data);
  public Object visit(ASThead node, Object data);
  public Object visit(ASTdisjunction node, Object data);
  public Object visit(ASTchoice_rule node, Object data);
  public Object visit(ASTchoice_elements node, Object data);
  public Object visit(ASTchoice_element node, Object data);
  public Object visit(ASTextendedSimpleAtomList node, Object data);
  public Object visit(ASTbody node, Object data);
  public Object visit(ASTvar node, Object data);
  public Object visit(ASTnonRelAtom node, Object data);
  public Object visit(ASTsimpleAtom node, Object data);
  public Object visit(ASTextendedNonRelAtom node, Object data);
  public Object visit(ASTarithmeticTerm node, Object data);
  public Object visit(ASTatomicArithmeticTerm node, Object data);
  public Object visit(ASTadditiveArithmeticTerm node, Object data);
  public Object visit(ASTmultiplicativeArithmeticTerm node, Object data);
  public Object visit(ASTsymbolicFunction node, Object data);
  public Object visit(ASTsymbolicConstant node, Object data);
  public Object visit(ASTsymbolicTerm node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTtermList node, Object data);
  public Object visit(ASTpredSymbol node, Object data);
  public Object visit(ASTatom node, Object data);
  public Object visit(ASTaggregate node, Object data);
  public Object visit(ASTaggregateElements node, Object data);
  public Object visit(ASTaggregateElement node, Object data);
  public Object visit(ASTaggregateFunction node, Object data);
  public Object visit(ASTatomSequence node, Object data);
  public Object visit(ASTcharacterRegularExpression node, Object data);
}
/* JavaCC - OriginalChecksum=16749072d0b53687997cb331efbe7cbd (do not edit this line) */
