/* Generated By:JavaCC: Do not edit this line. SparcTranslatorTreeConstants.java Version 5.0 */
package parser;

public interface SparcTranslatorTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSORTDEFINITIONS = 1;
  public int JJTSORTDEFINITION = 2;
  public int JJTSORTEXPRESSION = 3;
  public int JJTADDITIVESORTEXPRESSION = 4;
  public int JJTMULTIPLICATIVESORTEXPRESSION = 5;
  public int JJTREGULAREXPRESSION = 6;
  public int JJTCOMPLEXREGULAREXPRESSIONCHOICES = 7;
  public int JJTCOMPLEXREGULAREXPRESSION = 8;
  public int JJTCOMPLEXREGULAREXPRESSIONREPEATABLEUNIT = 9;
  public int JJTCOMPLEXREGULAREXPRESSIONUNIT = 10;
  public int JJTCOMPLEXREGULAREXPRESSIONUNITIDENTIFIER = 11;
  public int JJTVOID = 12;
  public int JJTREPEATITION = 13;
  public int JJTCHARACTERLIST = 14;
  public int JJTCONDITION = 15;
  public int JJTUNARYSORTEXPRESSION = 16;
  public int JJTSORTEXPRESSIONLIST = 17;
  public int JJTPREDICATEDECLARATIONS = 18;
  public int JJTPREDICATEDECLARATION = 19;
  public int JJTIDENTIFIERLIST = 20;
  public int JJTPROGRAMRULES = 21;
  public int JJTPROGRAMRULE = 22;
  public int JJTUNLABELEDPROGRAMRULE = 23;
  public int JJTCONSTRAINTPARAMS = 24;
  public int JJTUNLABELEDPROGRAMCRRULE = 25;
  public int JJTHEAD = 26;
  public int JJTDISJUNCTION = 27;
  public int JJTCHOICE_RULE = 28;
  public int JJTCHOICE_ELEMENTS = 29;
  public int JJTCHOICE_ELEMENT = 30;
  public int JJTEXTENDEDSIMPLEATOMLIST = 31;
  public int JJTBODY = 32;
  public int JJTVAR = 33;
  public int JJTNONRELATOM = 34;
  public int JJTSIMPLEATOM = 35;
  public int JJTEXTENDEDNONRELATOM = 36;
  public int JJTARITHMETICTERM = 37;
  public int JJTATOMICARITHMETICTERM = 38;
  public int JJTADDITIVEARITHMETICTERM = 39;
  public int JJTMULTIPLICATIVEARITHMETICTERM = 40;
  public int JJTSYMBOLICFUNCTION = 41;
  public int JJTSYMBOLICCONSTANT = 42;
  public int JJTSYMBOLICTERM = 43;
  public int JJTTERM = 44;
  public int JJTTERMLIST = 45;
  public int JJTPREDSYMBOL = 46;
  public int JJTATOM = 47;
  public int JJTAGGREGATE = 48;
  public int JJTAGGREGATEELEMENTS = 49;
  public int JJTAGGREGATEELEMENT = 50;
  public int JJTAGGREGATEFUNCTION = 51;
  public int JJTATOMSEQUENCE = 52;
  public int JJTCHARACTERREGULAREXPRESSION = 53;


  public String[] jjtNodeName = {
    "program",
    "sortDefinitions",
    "sortDefinition",
    "sortExpression",
    "additiveSortExpression",
    "multiplicativeSortExpression",
    "regularExpression",
    "complexRegularExpressionChoices",
    "complexRegularExpression",
    "complexRegularExpressionRepeatableUnit",
    "complexRegularExpressionUnit",
    "complexRegularExpressionUnitIdentifier",
    "void",
    "repeatition",
    "characterList",
    "condition",
    "unarySortExpression",
    "sortExpressionList",
    "predicateDeclarations",
    "predicateDeclaration",
    "identifierList",
    "programRules",
    "programRule",
    "unlabeledProgramRule",
    "constraintParams",
    "unlabeledProgramCrRule",
    "head",
    "disjunction",
    "choice_rule",
    "choice_elements",
    "choice_element",
    "extendedSimpleAtomList",
    "body",
    "var",
    "nonRelAtom",
    "simpleAtom",
    "extendedNonRelAtom",
    "arithmeticTerm",
    "atomicArithmeticTerm",
    "additiveArithmeticTerm",
    "multiplicativeArithmeticTerm",
    "symbolicFunction",
    "symbolicConstant",
    "symbolicTerm",
    "term",
    "termList",
    "predSymbol",
    "atom",
    "aggregate",
    "aggregateElements",
    "aggregateElement",
    "aggregateFunction",
    "atomSequence",
    "characterRegularExpression",
  };
}
/* JavaCC - OriginalChecksum=0309b218e85892f8917fc9ca95f5eb9e (do not edit this line) */
