#maxint=1000.
occurs(put(X_G,Y_G)):-action(put(X_G,Y_G)).
action(put(b0,b1)).
action(put(b3,b1)).
action(put(b0,b2)).
action(put(b3,t)).
action(put(b0,b3)).
action(put(b3,b2)).
action(put(b0,b0)).
action(put(b1,b1)).
action(put(b1,b2)).
action(put(b1,b3)).
action(put(b3,b3)).
action(put(b2,b2)).
action(put(b2,b1)).
action(put(b2,b0)).
action(put(b1,t)).
action(put(b2,b3)).
action(put(b2,t)).
action(put(b1,b0)).
action(put(b0,t)).
action(put(b3,b0)).
