link(ffh,ff,ffha).
link(ffh,ff,ffhb).
link(ff,ffj,ffdummy).
link(ffj,ff12j,ffi12).
link(ffj,ff345j,ffi345).
link(ff12j,f1u,ffm1).
link(ff12j,f1f,ffm1).
link(ff12j,f1l,ffm1).
link(ff12j,f1d,ffm1).
link(ff12j,f2u,ffm2).
link(ff12j,f2f,ffm2).
link(ff12j,f2r,ffm2).
link(ff12j,f2d,ffm2).
link(ff345j,f3u,ffm3).
link(ff345j,f3f,ffm3).
link(ff345j,f3l,ffm3).
link(ff345j,f3d,ffm3).
link(ff345j,f4r,ffm4).
link(ff345j,f4d,ffm4).
link(ff345j,f5l,ffm5).
link(ff345j,f5r,ffm5).
link(lfh,lf,lfha).
link(lfh,lf,lfhb).
link(lf,lfj,lfdummy).
link(lfj,lf12j,lfi12).
link(lfj,lf345j,lfi345a).
link(lfj,lf345j,lfi345b).
link(lf12j,l1u,lfm1).
link(lf12j,l1a,lfm1).
link(lf12j,l1l,lfm1).
link(lf12j,l2u,lfm2).
link(lf12j,l2d,lfm2).
link(lf12j,l2l,lfm2).
link(lf12j,fxfeed,lfx12).
link(fxfeed,lf12j,lfx12).
link(lf345j,l3a,lfm3).
link(lf345j,l3d,lfm3).
link(lf345j,l3l,lfm3).
link(lf345j,l4u,lfm4).
link(lf345j,l4d,lfm4).
link(lf345j,l4l,lfm4).
link(lf345j,l5d,lfm5).
link(lf345j,l5l,lfm5).
link(lf345j,fxfeed,lfx345).
link(fxfeed,lf345j,lfx345).
link(rfh,rf,rfha).
link(rfh,rf,rfhb).
link(rf,rfj,rfdummy).
link(rfj,rf12j,rfi12).
link(rfj,rf345j,rfi345a).
link(rfj,rf345j,rfi345b).
link(rf12j,r1u,rfm1).
link(rf12j,r1a,rfm1).
link(rf12j,r1r,rfm1).
link(rf12j,r2u,rfm2).
link(rf12j,r2d,rfm2).
link(rf12j,r2r,rfm2).
link(rf12j,fxfeed,rfx12).
link(fxfeed,rf12j,rfx12).
link(rf345j,r3a,rfm3).
link(rf345j,r3d,rfm3).
link(rf345j,r3r,rfm3).
link(rf345j,r4u,rfm4).
link(rf345j,r4d,rfm4).
link(rf345j,r4r,rfm4).
link(rf345j,r5d,rfm5).
link(rf345j,r5r,rfm5).
link(rf345j,fxfeed,rfx345).
link(fxfeed,rf345j,rfx345).
link(foh,fo,foha).
link(foh,fo,fohb).
link(fo,foj,fodummy).
link(foj,fo12j,foi12).
link(foj,fo345j,foi345).
link(fo12j,f1u,fom1).
link(fo12j,f1f,fom1).
link(fo12j,f1l,fom1).
link(fo12j,f1d,fom1).
link(fo12j,f2u,fom2).
link(fo12j,f2f,fom2).
link(fo12j,f2r,fom2).
link(fo12j,f2d,fom2).
link(fo345j,f3u,fom3).
link(fo345j,f3f,fom3).
link(fo345j,f3l,fom3).
link(fo345j,f3d,fom3).
link(fo345j,f4r,fom4).
link(fo345j,f4d,fom4).
link(fo345j,f5l,fom5).
link(fo345j,f5r,fom5).
link(loh,lo,loha).
link(loh,lo,lohb).
link(lo,loj,lodummy).
link(loj,lo12j,loi12).
link(loj,lo345j,loi345a).
link(loj,lo345j,loi345b).
link(lo12j,l1u,lom1).
link(lo12j,l1a,lom1).
link(lo12j,l1l,lom1).
link(lo12j,l2u,lom2).
link(lo12j,l2d,lom2).
link(lo12j,l2l,lom2).
link(lo12j,oxfeed,lox12).
link(oxfeed,lo12j,lox12).
link(lo345j,l3a,lom3).
link(lo345j,l3d,lom3).
link(lo345j,l3l,lom3).
link(lo345j,l4u,lom4).
link(lo345j,l4d,lom4).
link(lo345j,l4l,lom4).
link(lo345j,l5d,lom5).
link(lo345j,l5l,lom5).
link(lo345j,oxfeed,lox345).
link(oxfeed,lo345j,lox345).
link(roh,ro,roha).
link(roh,ro,rohb).
link(ro,roj,rodummy).
link(roj,ro12j,roi12).
link(roj,ro345j,roi345a).
link(roj,ro345j,roi345b).
link(ro12j,r1u,rom1).
link(ro12j,r1a,rom1).
link(ro12j,r1r,rom1).
link(ro12j,r2u,rom2).
link(ro12j,r2d,rom2).
link(ro12j,r2r,rom2).
link(ro12j,oxfeed,rox12).
link(oxfeed,ro12j,rox12).
link(ro345j,r3a,rom3).
link(ro345j,r3d,rom3).
link(ro345j,r3r,rom3).
link(ro345j,r4u,rom4).
link(ro345j,r4d,rom4).
link(ro345j,r4r,rom4).
link(ro345j,r5d,rom5).
link(ro345j,r5r,rom5).
link(ro345j,oxfeed,rox345).
link(oxfeed,ro345j,rox345).
tank_of(ffh,fwd_rcs).
tank_of(ff,fwd_rcs).
tank_of(foh,fwd_rcs).
tank_of(fo,fwd_rcs).
tank_of(lfh,left_rcs).
tank_of(lf,left_rcs).
tank_of(loh,left_rcs).
tank_of(lo,left_rcs).
tank_of(rfh,right_rcs).
tank_of(rf,right_rcs).
tank_of(roh,right_rcs).
tank_of(ro,right_rcs).
tank_of(ohmsf,ohms).
tank_of(ohmso,ohms).
jet_of(f1u,fwd_rcs).
jet_of(f1f,fwd_rcs).
jet_of(f1l,fwd_rcs).
jet_of(f1d,fwd_rcs).
jet_of(f2u,fwd_rcs).
jet_of(f2f,fwd_rcs).
jet_of(f2r,fwd_rcs).
jet_of(f2d,fwd_rcs).
jet_of(f3u,fwd_rcs).
jet_of(f3f,fwd_rcs).
jet_of(f3l,fwd_rcs).
jet_of(f3d,fwd_rcs).
jet_of(f4r,fwd_rcs).
jet_of(f4d,fwd_rcs).
jet_of(l1u,left_rcs).
jet_of(l1a,left_rcs).
jet_of(l1l,left_rcs).
jet_of(l2u,left_rcs).
jet_of(l2l,left_rcs).
jet_of(l2d,left_rcs).
jet_of(l3a,left_rcs).
jet_of(l3l,left_rcs).
jet_of(l3d,left_rcs).
jet_of(l4u,left_rcs).
jet_of(l4l,left_rcs).
jet_of(l4d,left_rcs).
jet_of(r1u,right_rcs).
jet_of(r1a,right_rcs).
jet_of(r1r,right_rcs).
jet_of(r2u,right_rcs).
jet_of(r2r,right_rcs).
jet_of(r2d,right_rcs).
jet_of(r3a,right_rcs).
jet_of(r3r,right_rcs).
jet_of(r3d,right_rcs).
jet_of(r4u,right_rcs).
jet_of(r4r,right_rcs).
jet_of(r4d,right_rcs).
vernier_of(f5l,fwd_rcs).
vernier_of(f5r,fwd_rcs).
vernier_of(l5l,left_rcs).
vernier_of(l5d,left_rcs).
vernier_of(r5r,right_rcs).
vernier_of(r5d,right_rcs).
direction(f1f,forward).
direction(f2f,forward).
direction(f3f,forward).
direction(f1u,up).
direction(f2u,up).
direction(f3u,up).
direction(l1u,up).
direction(l2u,up).
direction(l4u,up).
direction(r1u,up).
direction(r2u,up).
direction(r4u,up).
direction(f1d,down).
direction(f2d,down).
direction(f3d,down).
direction(f4d,down).
direction(l2d,down).
direction(l3d,down).
direction(l4d,down).
direction(r2d,down).
direction(r3d,down).
direction(r4d,down).
direction(l1a,aft).
direction(l3a,aft).
direction(r1a,aft).
direction(r3a,aft).
direction(f1l,left).
direction(f3l,left).
direction(l1l,left).
direction(l2l,left).
direction(l3l,left).
direction(l4l,left).
direction(f2r,right).
direction(f4r,right).
direction(r1r,right).
direction(r2r,right).
direction(r3r,right).
direction(r4r,right).
pair_of_jets(f1d,f2d).
pair_of_jets(f1d,f4d).
pair_of_jets(f3d,f2d).
pair_of_jets(f3d,f4d).
h(leaking(N1_G),T_G):-link(N1_G,N2_G,V_G),has_leak(V_G),h(in_state(V_G,open),T_G),s_gen0(V_G).
h(leaking(N1_G),T_G):-link(N1_G,N2_G,V_G),h(in_state(V_G,open),T_G),h(leaking(N2_G),T_G),s_gen0(V_G).
h(pressurized_by(N1_G,X_G),T_G):-not  tank_of(N1_G,R_G),link(N2_G,N1_G,V_G),h(in_state(V_G,open),T_G),tank_of(X_G,R_G),h(pressurized_by(N2_G,X_G),T_G),not  h(leaking(N1_G),T_G),s_gen0(V_G).
h(pressurized_by(N1_G,X_G),T_G):-tank_of(N1_G,R_G),link(N2_G,N1_G,V_G),h(in_state(V_G,open),T_G),tank_of(X_G,R_G),h(pressurized_by(N2_G,X_G),T_G),s_gen0(V_G).
:-tank_of(X_G,R_G),tank_of(Y_G,R1_G),X_G!=Y_G,h(pressurized_by(fxfeed,X_G),T_G),h(pressurized_by(fxfeed,Y_G),T_G).
:-tank_of(X_G,R_G),tank_of(Y_G,R1_G),X_G!=Y_G,h(pressurized_by(oxfeed,X_G),T_G),h(pressurized_by(oxfeed,Y_G),T_G).
h(ready_to_fire(J_G),T_G):-jet_of(J_G,R_G),tank_of(TK1_G,R1_G),tank_of(TK2_G,R2_G),TK1_G!=TK2_G,h(pressurized_by(J_G,TK1_G),T_G),h(pressurized_by(J_G,TK2_G),T_G),not  damaged(J_G).
h(fire_vernier(J_G),T_G):-vernier_of(J_G,R_G),tank_of(TK1_G,R_G),tank_of(TK2_G,R_G),TK1_G!=TK2_G,h(pressurized_by(J_G,TK1_G),T_G),h(pressurized_by(J_G,TK2_G),T_G),not  damaged(J_G).
h(maneuver_of(X_G,S_G),T_G):-done(X_G,S_G),s_gen1(T_G).
h(maneuver_of(plus_x,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,aft),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_x,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,aft),h(ready_to_fire(J_G),T_G).
done(plus_x,fwd_rcs).
h(maneuver_of(minus_x,fwd_rcs),T_G):-jet_of(J1_G,fwd_rcs),jet_of(J2_G,fwd_rcs),direction(J1_G,forward),direction(J2_G,forward),J1_G!=J2_G,h(ready_to_fire(J1_G),T_G),h(ready_to_fire(J2_G),T_G).
done(minus_x,left_rcs).
done(minus_x,right_rcs).
h(maneuver_of(plus_y,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,left),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_y,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,left),h(ready_to_fire(J_G),T_G).
done(plus_y,right_rcs).
h(maneuver_of(minus_y,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,right),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_y,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,right),h(ready_to_fire(J_G),T_G).
done(minus_y,left_rcs).
h(maneuver_of(plus_z,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_z,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_z,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_z,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_z,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_z,fwd_rcs),T_G):-pair_of_jets(J1_G,J2_G),h(ready_to_fire(J1_G),T_G),h(ready_to_fire(J2_G),T_G).
h(maneuver_of(plus_roll,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_roll,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
done(plus_roll,fwd_rcs).
h(maneuver_of(minus_roll,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_roll,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
done(minus_roll,fwd_rcs).
h(maneuver_of(plus_pitch,fwd_rcs),T_G):-pair_of_jets(J1_G,J2_G),h(ready_to_fire(J1_G),T_G),h(ready_to_fire(J2_G),T_G).
h(maneuver_of(plus_pitch,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_pitch,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_pitch,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,up),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_pitch,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_pitch,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,down),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_yaw,right_rcs),T_G):-jet_of(J_G,right_rcs),direction(J_G,right),h(ready_to_fire(J_G),T_G).
h(maneuver_of(plus_yaw,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,left),h(ready_to_fire(J_G),T_G).
done(plus_yaw,left_rcs).
h(maneuver_of(minus_yaw,left_rcs),T_G):-jet_of(J_G,left_rcs),direction(J_G,left),h(ready_to_fire(J_G),T_G).
h(maneuver_of(minus_yaw,fwd_rcs),T_G):-jet_of(J_G,fwd_rcs),direction(J_G,right),h(ready_to_fire(J_G),T_G).
done(minus_yaw,right_rcs).
h(pressurized_by(X_G,X_G),T1_G):-next(T_G,T1_G),tank_of(X_G,R_G),h(pressurized_by(X_G,X_G),T_G),not  nh(pressurized_by(X_G,X_G),T1_G).
:-link(N2_G,N_G,V_G),tank_of(X_G,R_G),h(pressurized_by(N_G,X_G),T_G),nh(pressurized_by(N_G,X_G),T_G).
:-link(N_G,N2_G,V_G),h(leaking(N_G),T_G),nh(leaking(N_G),T_G).
stuck_device(D_G):-stuck(D_G,S_G).
:-controls(Sw_G,V_G),h(ab_input(V_G),0).
h(in_state(Sw_G,S_G),T1_G):-next(T_G,T1_G),of_type(Sw_G,v_switch),state_of(S_G,v_switch),occurs(flip(Sw_G,S_G),T_G),not  stuck_device(Sw_G),s_gen2(Sw_G),s_gen3(S_G).
h(in_state(V_G,S_G),T1_G):-next(T_G,T1_G),controls(Sw_G,V_G),h(in_state(Sw_G,gpc),T_G),occurs(CC_G,T_G),commands(CC_G,V_G,S_G),not  stuck_device(V_G),not  bad_circuitry(V_G),s_gen2(Sw_G),s_gen3(S_G),s_gen0(V_G).
h(in_state(V_G,S_G),T_G):-controls(Sw_G,V_G),h(in_state(Sw_G,S_G),T_G),state_of(S_G,v_switch),S_G!=gpc,not  h(ab_input(V_G),T_G),not  stuck_device(V_G),not  bad_circuitry(V_G),s_gen2(Sw_G),s_gen3(S_G),s_gen0(V_G).
h(ab_input(V_G),T1_G):-next(T_G,T1_G),controls(Sw_G,V_G),h(in_state(Sw_G,S_G),T_G),occurs(CC_G,T_G),commands(CC_G,V_G,P_G),state_of(S_G,v_switch),S_G!=gpc,S_G!=P_G,not  bad_circuitry(V_G),s_gen2(Sw_G),s_gen3(S_G).
h(in_state(D_G,S_G),0):-stuck(D_G,S_G),s_gen3(S_G).
state_of(open,v_switch).
state_of(closed,v_switch).
state_of(gpc,v_switch).
state_of(open,valve).
state_of(closed,valve).
opposite_state(open,closed).
opposite_state(closed,open).
of_type(V_G,valve):-controls(D_G,V_G),s_gen0(V_G).
of_type(D_G,v_switch):-controls(D_G,V_G),s_gen2(D_G).
of_type(V_G,valve):-dummy_valve(V_G),s_gen0(V_G).
dummy_valve(ffdummy).
dummy_valve(fodummy).
dummy_valve(lfdummy).
dummy_valve(lodummy).
dummy_valve(rfdummy).
dummy_valve(rodummy).
controls(D_G,V_G):-controls_3(D_G,V_G,C_G).
controls_3(fha,ffha,fhca).
controls_3(fha,foha,fhca).
controls_3(fhb,ffhb,fhcb).
controls_3(fhb,fohb,fhcb).
controls_3(fi12,ffi12,fic12).
controls_3(fi12,foi12,fic12).
controls_3(fi345,ffi345,fic345).
controls_3(fi345,foi345,fic345).
controls_3(fm1,ffm1,fmc1).
controls_3(fm1,fom1,fmc1).
controls_3(fm2,ffm2,fmc2).
controls_3(fm2,fom2,fmc2).
controls_3(fm3,ffm3,fmc3).
controls_3(fm3,fom3,fmc3).
controls_3(fm4,ffm4,fmc4).
controls_3(fm4,fom4,fmc4).
controls_3(fm5,ffm5,fmc5).
controls_3(fm5,fom5,fmc5).
controls_3(lha,lfha,lhca).
controls_3(lha,loha,lhca).
controls_3(lhb,lfhb,lhcb).
controls_3(lhb,lohb,lhcb).
controls_3(li12,lfi12,lic12).
controls_3(li12,loi12,lic12).
controls_3(li345a,lfi345a,lic345a).
controls_3(li345a,loi345a,lic345a).
controls_3(li345b,lfi345b,lic345b).
controls_3(li345b,loi345b,lic345b).
controls_3(lm1,lfm1,lmc1).
controls_3(lm1,lom1,lmc1).
controls_3(lm2,lfm2,lmc2).
controls_3(lm2,lom2,lmc2).
controls_3(lm3,lfm3,lmc3).
controls_3(lm3,lom3,lmc3).
controls_3(lm4,lfm4,lmc4).
controls_3(lm4,lom4,lmc4).
controls_3(lm5,lfm5,lmc5).
controls_3(lm5,lom5,lmc5).
controls_3(lx12,lfx12,lxc12).
controls_3(lx12,lox12,lxc12).
controls_3(lx345,lfx345,lxc345).
controls_3(lx345,lox345,lxc345).
controls_3(rha,rfha,rhca).
controls_3(rha,roha,rhca).
controls_3(rhb,rfhb,rhcb).
controls_3(rhb,rohb,rhcb).
controls_3(ri12,rfi12,ric12).
controls_3(ri12,roi12,ric12).
controls_3(ri345a,rfi345a,ric345a).
controls_3(ri345a,roi345a,ric345a).
controls_3(ri345b,rfi345b,ric345b).
controls_3(ri345b,roi345b,ric345b).
controls_3(rm1,rfm1,rmc1).
controls_3(rm1,rom1,rmc1).
controls_3(rm2,rfm2,rmc2).
controls_3(rm2,rom2,rmc2).
controls_3(rm3,rfm3,rmc3).
controls_3(rm3,rom3,rmc3).
controls_3(rm4,rfm4,rmc4).
controls_3(rm4,rom4,rmc4).
controls_3(rm5,rfm5,rmc5).
controls_3(rm5,rom5,rmc5).
controls_3(rx12,rfx12,rxc12).
controls_3(rx12,rox12,rxc12).
controls_3(rx345,rfx345,rxc345).
controls_3(rx345,rox345,rxc345).
basic_command(opena_ffha,ffha,open).
basic_command(opena_ffha,foha,open).
basic_command(closea_ffha,ffha,closed).
basic_command(closea_ffha,foha,closed).
basic_command(opena_ffhb,ffhb,open).
basic_command(opena_ffhb,fohb,open).
basic_command(closea_ffhb,ffhb,closed).
basic_command(closea_ffhb,fohb,closed).
basic_command(opena_ffi12,ffi12,open).
basic_command(opena_foi12,foi12,open).
basic_command(opena_ffi345,ffi345,open).
basic_command(opena_foi345,foi345,open).
basic_command(open_ffm1,ffm1,open).
basic_command(open_ffm1,fom1,open).
basic_command(closea_ffm1,ffm1,closed).
basic_command(closea_ffm1,fom1,closed).
basic_command(closeb_ffm1,ffm1,closed).
basic_command(closeb_ffm1,fom1,closed).
basic_command(open_ffm2,ffm2,open).
basic_command(open_ffm2,fom2,open).
basic_command(closea_ffm2,ffm2,closed).
basic_command(closea_ffm2,fom2,closed).
basic_command(closeb_ffm2,ffm2,closed).
basic_command(closeb_ffm2,fom2,closed).
basic_command(open_ffm3,ffm3,open).
basic_command(open_ffm3,fom3,open).
basic_command(closea_ffm3,ffm3,closed).
basic_command(closea_ffm3,fom3,closed).
basic_command(closeb_ffm3,ffm3,closed).
basic_command(closeb_ffm3,fom3,closed).
basic_command(open_ffm4,ffm4,open).
basic_command(open_ffm4,fom4,open).
basic_command(closea_ffm4,ffm4,closed).
basic_command(closea_ffm4,fom4,closed).
basic_command(closeb_ffm4,ffm4,closed).
basic_command(closeb_ffm4,fom4,closed).
basic_command(opena_lfha,lfha,open).
basic_command(opena_lfha,loha,open).
basic_command(closea_lfha,lfha,closed).
basic_command(closea_lfha,loha,closed).
basic_command(opena_lfhb,lfhb,open).
basic_command(opena_lfhb,lohb,open).
basic_command(closea_lfhb,lfhb,closed).
basic_command(closea_lfhb,lohb,closed).
basic_command(opena_li12,lfi12,open).
basic_command(opena_li12,loi12,open).
basic_command(openb_lfi12,lfi12,open).
basic_command(openb_loi12,loi12,open).
basic_command(opena_lx12,lfx12,open).
basic_command(opena_lx12,lox12,open).
basic_command(openb_lfx12,lfx12,open).
basic_command(openb_lox12,lox12,open).
basic_command(open_lfi345a,lfi345a,open).
basic_command(open_loi345a,loi345a,open).
basic_command(close_lfi345a,lfi345a,closed).
basic_command(close_loi345a,loi345a,closed).
basic_command(open_lfi345b,lfi345b,open).
basic_command(open_loi345b,loi345b,open).
basic_command(close_lfi345b,lfi345b,closed).
basic_command(close_loi345b,loi345b,closed).
basic_command(open_lfx345,lfx345,open).
basic_command(open_lox345,lox345,open).
basic_command(close_lfx345,lfx345,closed).
basic_command(close_lox345,lox345,closed).
basic_command(open_lfm1,lfm1,open).
basic_command(open_lfm1,lom1,open).
basic_command(closea_lfm1,lfm1,closed).
basic_command(closea_lfm1,lom1,closed).
basic_command(closeb_lfm1,lfm1,closed).
basic_command(closeb_lfm1,lom1,closed).
basic_command(open_lfm2,lfm2,open).
basic_command(open_lfm2,lom2,open).
basic_command(closea_lfm2,lfm2,closed).
basic_command(closea_lfm2,lom2,closed).
basic_command(closeb_lfm2,lfm2,closed).
basic_command(closeb_lfm2,lom2,closed).
basic_command(open_lfm3,lfm3,open).
basic_command(open_lfm3,lom3,open).
basic_command(closea_lfm3,lfm3,closed).
basic_command(closea_lfm3,lom3,closed).
basic_command(closeb_lfm3,lfm3,closed).
basic_command(closeb_lfm3,lom3,closed).
basic_command(open_lfm4,lfm4,open).
basic_command(open_lfm4,lom4,open).
basic_command(closea_lfm4,lfm4,closed).
basic_command(closea_lfm4,lom4,closed).
basic_command(closeb_lfm4,lfm4,closed).
basic_command(closeb_lfm4,lom4,closed).
basic_command(opena_rfha,rfha,open).
basic_command(opena_rfha,roha,open).
basic_command(closea_rfha,rfha,closed).
basic_command(closea_rfha,roha,closed).
basic_command(opena_rfhb,rfhb,open).
basic_command(opena_rfhb,rohb,open).
basic_command(closea_rfhb,rfhb,closed).
basic_command(closea_rfhb,rohb,closed).
basic_command(opena_ri12,rfi12,open).
basic_command(opena_ri12,roi12,open).
basic_command(openb_rfi12,rfi12,open).
basic_command(openb_roi12,roi12,open).
basic_command(opena_rx12,rfx12,open).
basic_command(opena_rx12,rox12,open).
basic_command(openb_rfx12,rfx12,open).
basic_command(openb_rox12,rox12,open).
basic_command(open_rfi345a,rfi345a,open).
basic_command(open_roi345a,roi345a,open).
basic_command(close_rfi345a,rfi345a,closed).
basic_command(close_roi345a,roi345a,closed).
basic_command(open_rfi345b,rfi345b,open).
basic_command(open_roi345b,roi345b,open).
basic_command(close_rfi345b,rfi345b,closed).
basic_command(close_roi345b,roi345b,closed).
basic_command(open_rfx345,rfx345,open).
basic_command(open_rox345,rox345,open).
basic_command(close_rfx345,rfx345,closed).
basic_command(close_rox345,rox345,closed).
basic_command(open_rfm1,rfm1,open).
basic_command(open_rfm1,rom1,open).
basic_command(closea_rfm1,rfm1,closed).
basic_command(closea_rfm1,rom1,closed).
basic_command(closeb_rfm1,rfm1,closed).
basic_command(closeb_rfm1,rom1,closed).
basic_command(open_rfm2,rfm2,open).
basic_command(open_rfm2,rom2,open).
basic_command(closea_rfm2,rfm2,closed).
basic_command(closea_rfm2,rom2,closed).
basic_command(closeb_rfm2,rfm2,closed).
basic_command(closeb_rfm2,rom2,closed).
basic_command(open_rfm3,rfm3,open).
basic_command(open_rfm3,rom3,open).
basic_command(closea_rfm3,rfm3,closed).
basic_command(closea_rfm3,rom3,closed).
basic_command(closeb_rfm3,rfm3,closed).
basic_command(closeb_rfm3,rom3,closed).
basic_command(open_rfm4,rfm4,open).
basic_command(open_rfm4,rom4,open).
basic_command(closea_rfm4,rfm4,closed).
basic_command(closea_rfm4,rom4,closed).
basic_command(closeb_rfm4,rfm4,closed).
basic_command(closeb_rfm4,rom4,closed).
commands(CC_G,V_G,S_G):-basic_command(CC_G,V_G,S_G),s_gen4(CC_G).
commands(cc(closea_fi12,closeb_ffi12),ffi12,closed).
commands(cc(closea_fi12,closeb_foi12),foi12,closed).
commands(cc(opena_ffm5,openb_ffm5),ffm5,open).
commands(cc(opena_ffm5,openb_ffm5),fom5,open).
commands(cc(closea_ffm5,closeb_ffm5),ffm5,closed).
commands(cc(closea_ffm5,closeb_ffm5),fom5,closed).
commands(cc(closea_li12,closeb_lfi12),lfi12,closed).
commands(cc(closea_li12,closeb_loi12),loi12,closed).
commands(cc(close_lx12,close_lfx12),lfx12,closed).
commands(cc(close_lx12,close_lox12),lox12,closed).
commands(cc(opena_lfm5,openb_lfm5),lfm5,open).
commands(cc(opena_lfm5,openb_lfm5),lom5,open).
commands(cc(closea_lfm5,closeb_lfm5),lfm5,closed).
commands(cc(closea_lfm5,closeb_lfm5),lom5,closed).
commands(cc(closea_ri12,closeb_rfi12),rfi12,closed).
commands(cc(closea_ri12,closeb_roi12),roi12,closed).
commands(cc(close_rx12,close_rfx12),rfx12,closed).
commands(cc(close_rx12,close_rox12),rox12,closed).
commands(cc(opena_rfm5,openb_rfm5),rfm5,open).
commands(cc(opena_rfm5,openb_rfm5),rom5,open).
commands(cc(closea_rfm5,closeb_rfm5),rfm5,closed).
commands(cc(closea_rfm5,closeb_rfm5),rom5,closed).
:-of_type(Sw_G,v_switch),state_of(S_G,v_switch),h(in_state(Sw_G,S_G),T_G),occurs(flip(Sw_G,S_G),T_G),s_gen2(Sw_G),s_gen3(S_G).
h(in_state(D_G,S_G),T1_G):-next(T_G,T1_G),of_type(D_G,Dev_G),state_of(S_G,Dev_G),h(in_state(D_G,S_G),T_G),not  nh(in_state(D_G,S_G),T1_G),s_gen3(S_G).
nh(in_state(D_G,S_G),T_G):-of_type(D_G,Dev_G),state_of(S_G,Dev_G),state_of(S1_G,Dev_G),S_G!=S1_G,h(in_state(D_G,S1_G),T_G),s_gen3(S1_G),s_gen3(S_G).
:-of_type(D_G,Dev_G),state_of(S_G,Dev_G),h(in_state(D_G,S_G),T_G),nh(in_state(D_G,S_G),T_G),s_gen3(S_G).
next(T_G,T1_G):-T1_G=T_G+1,s_gen1(T1_G),s_gen1(T_G).
action_of(flip(Sw_G,S_G),R_G):-of_type_3(Sw_G,R_G,v_switch),state_of(S_G,v_switch),s_gen2(Sw_G).
action_of(CC_G,R_G):-commands(CC_G,V_G,S_G),of_type_3(V_G,R_G,valve),s_gen0(V_G).
appl(r_0(A_G,T_G,R_G))|-appl(r_0(A_G,T_G,R_G)):-action_of(A_G,R_G),s_gen1(T_G).
:~appl(r_0(A_G,T_G,R_G)),action_of(A_G,R_G),s_gen1(T_G).
occurs(A_G,T_G):-action_of(A_G,R_G),s_gen1(T_G),appl(r_0(A_G,T_G,R_G)).
:-A1_G!=A2_G,occurs(A1_G,T_G),occurs(A2_G,T_G),action_of(A1_G,R_G),action_of(A2_G,R_G).
:-action_of(A_G,R_G),occurs(A_G,T_G),not  involved(R_G,T_G).
involved(R_G,T_G):-not  goal(T_G,R_G),not  done_1(R_G),s_gen1(T_G),s_gen5(R_G).
aft_system(left_rcs).
aft_system(right_rcs).
appl(r1)|-appl(r1).
:~appl(r1).
use_xfeed(0):-appl(r1).
involved(AFT1_G,T_G):-aft_system(AFT1_G),aft_system(AFT2_G),AFT2_G!=AFT1_G,not  goal(T_G,AFT2_G),not  done_1(AFT2_G),use_xfeed(0),s_gen1(T_G).
type_cc(closea_fi12).
type_cc(closeb_ffi12).
type_cc(closeb_foi12).
type_cc(closea_li12).
type_cc(closeb_lfi12).
type_cc(closeb_loi12).
type_cc(close_lx12).
type_cc(close_lfx12).
type_cc(close_lox12).
type_cc(closea_ri12).
type_cc(closeb_rfi12).
type_cc(closeb_roi12).
type_cc(close_rx12).
type_cc(close_rfx12).
type_cc(close_rox12).
type_cc(opena_ffm5).
type_cc(openb_ffm5).
type_cc(opena_lfm5).
type_cc(openb_lfm5).
type_cc(opena_rfm5).
type_cc(openb_rfm5).
type_cc(closea_ffm5).
type_cc(closeb_ffm5).
type_cc(closea_lfm5).
type_cc(closeb_lfm5).
type_cc(closea_rfm5).
type_cc(closeb_rfm5).
goal_1(0):-goal(T1_G,left_rcs),goal(T2_G,right_rcs),goal(T3_G,fwd_rcs).
goal(T_G,S_G):-done_1(S_G),s_gen1(T_G).
:-not  goal_1(0).
of_type_3(fha,fwd_rcs,v_switch).
of_type_3(fhb,fwd_rcs,v_switch).
of_type_3(fi12,fwd_rcs,v_switch).
of_type_3(fi345,fwd_rcs,v_switch).
of_type_3(fm1,fwd_rcs,v_switch).
of_type_3(fm2,fwd_rcs,v_switch).
of_type_3(fm3,fwd_rcs,v_switch).
of_type_3(fm4,fwd_rcs,v_switch).
of_type_3(fm5,fwd_rcs,v_switch).
of_type_3(lha,left_rcs,v_switch).
of_type_3(lhb,left_rcs,v_switch).
of_type_3(li12,left_rcs,v_switch).
of_type_3(li345a,left_rcs,v_switch).
of_type_3(li345b,left_rcs,v_switch).
of_type_3(lm1,left_rcs,v_switch).
of_type_3(lm2,left_rcs,v_switch).
of_type_3(lm3,left_rcs,v_switch).
of_type_3(lm4,left_rcs,v_switch).
of_type_3(lm5,left_rcs,v_switch).
of_type_3(lx12,left_rcs,v_switch).
of_type_3(lx345,left_rcs,v_switch).
of_type_3(rha,right_rcs,v_switch).
of_type_3(rhb,right_rcs,v_switch).
of_type_3(ri12,right_rcs,v_switch).
of_type_3(ri345a,right_rcs,v_switch).
of_type_3(ri345b,right_rcs,v_switch).
of_type_3(rm1,right_rcs,v_switch).
of_type_3(rm2,right_rcs,v_switch).
of_type_3(rm3,right_rcs,v_switch).
of_type_3(rm4,right_rcs,v_switch).
of_type_3(rm5,right_rcs,v_switch).
of_type_3(rx12,right_rcs,v_switch).
of_type_3(rx345,right_rcs,v_switch).
of_type_3(ffha,fwd_rcs,valve).
of_type_3(foha,fwd_rcs,valve).
of_type_3(ffhb,fwd_rcs,valve).
of_type_3(fohb,fwd_rcs,valve).
of_type_3(ffi12,fwd_rcs,valve).
of_type_3(foi12,fwd_rcs,valve).
of_type_3(ffi345,fwd_rcs,valve).
of_type_3(foi345,fwd_rcs,valve).
of_type_3(ffm1,fwd_rcs,valve).
of_type_3(fom1,fwd_rcs,valve).
of_type_3(ffm2,fwd_rcs,valve).
of_type_3(fom2,fwd_rcs,valve).
of_type_3(ffm3,fwd_rcs,valve).
of_type_3(fom3,fwd_rcs,valve).
of_type_3(ffm4,fwd_rcs,valve).
of_type_3(fom4,fwd_rcs,valve).
of_type_3(ffm5,fwd_rcs,valve).
of_type_3(fom5,fwd_rcs,valve).
of_type_3(lfha,left_rcs,valve).
of_type_3(loha,left_rcs,valve).
of_type_3(lfhb,left_rcs,valve).
of_type_3(lohb,left_rcs,valve).
of_type_3(lfi12,left_rcs,valve).
of_type_3(loi12,left_rcs,valve).
of_type_3(lfi345a,left_rcs,valve).
of_type_3(loi345a,left_rcs,valve).
of_type_3(lfi345b,left_rcs,valve).
of_type_3(loi345b,left_rcs,valve).
of_type_3(lfm1,left_rcs,valve).
of_type_3(lom1,left_rcs,valve).
of_type_3(lfm2,left_rcs,valve).
of_type_3(lom2,left_rcs,valve).
of_type_3(lfm3,left_rcs,valve).
of_type_3(lom3,left_rcs,valve).
of_type_3(lfm4,left_rcs,valve).
of_type_3(lom4,left_rcs,valve).
of_type_3(lfm5,left_rcs,valve).
of_type_3(lom5,left_rcs,valve).
of_type_3(lfx12,left_rcs,valve).
of_type_3(lox12,left_rcs,valve).
of_type_3(lfx345,left_rcs,valve).
of_type_3(lox345,left_rcs,valve).
of_type_3(rfha,right_rcs,valve).
of_type_3(roha,right_rcs,valve).
of_type_3(rfhb,right_rcs,valve).
of_type_3(rohb,right_rcs,valve).
of_type_3(rfi12,right_rcs,valve).
of_type_3(roi12,right_rcs,valve).
of_type_3(rfi345a,right_rcs,valve).
of_type_3(roi345a,right_rcs,valve).
of_type_3(rfi345b,right_rcs,valve).
of_type_3(roi345b,right_rcs,valve).
of_type_3(rfm1,right_rcs,valve).
of_type_3(rom1,right_rcs,valve).
of_type_3(rfm2,right_rcs,valve).
of_type_3(rom2,right_rcs,valve).
of_type_3(rfm3,right_rcs,valve).
of_type_3(rom3,right_rcs,valve).
of_type_3(rfm4,right_rcs,valve).
of_type_3(rom4,right_rcs,valve).
of_type_3(rfm5,right_rcs,valve).
of_type_3(rom5,right_rcs,valve).
of_type_3(rfx12,right_rcs,valve).
of_type_3(rox12,right_rcs,valve).
of_type_3(rfx345,right_rcs,valve).
of_type_3(rox345,right_rcs,valve).
of_type_3(V_G,R_G,valve):-dummy_valve_2(V_G,R_G),s_gen0(V_G).
dummy_valve_2(ffdummy,fwd_rcs).
dummy_valve_2(fodummy,fwd_rcs).
dummy_valve_2(lfdummy,left_rcs).
dummy_valve_2(lodummy,left_rcs).
dummy_valve_2(rfdummy,right_rcs).
dummy_valve_2(rodummy,right_rcs).
:-action_of(A_G,R_G),T1_G!=T2_G,occurs(A_G,T1_G),occurs(A_G,T2_G).
:-occurs(flip(Sw_G,S_G),T_G),controls(Sw_G,V_G),commands(CC_G,V_G,S_G),occurs(CC_G,T1_G).
:-link(N1_G,N2_G,V1_G),link(N1_G,N2_G,V2_G),V1_G!=V2_G,h(in_state(V1_G,open),T_G),h(in_state(V2_G,open),T_G),not  stuck(V1_G,open),not  stuck(V2_G,open),not  h(in_state(V1_G,open),0),not  h(in_state(V2_G,open),0),s_gen0(V2_G),s_gen0(V1_G).
:-T2_G>T1_G,commands(CC1_G,V_G,S1_G),occurs(CC1_G,T1_G),opposite_state(S1_G,S2_G),commands(CC2_G,V_G,S2_G),occurs(CC2_G,T2_G).
:-T2_G>T1_G,controls(Sw_G,V_G),occurs(flip(Sw_G,S_G),T1_G),opposite_state(S_G,S1_G),occurs(flip(Sw_G,S1_G),T2_G).
:-T2_G!=T1_G,commands(CC_G,V_G,S1_G),occurs(CC_G,T1_G),opposite_state(S1_G,S2_G),controls(Sw_G,V_G),occurs(flip(Sw_G,S2_G),T2_G).
:-controls(Sw_G,V1_G),controls(Sw_G,V2_G),V1_G!=V2_G,h(in_state(V1_G,S1_G),T_G),h(in_state(V2_G,S1_G),T_G),state_of(S1_G,valve),occurs(flip(Sw_G,S1_G),T_G),s_gen0(V2_G),s_gen0(V1_G),s_gen3(S1_G).
:-occurs(CC_G,T_G),commands(CC_G,V1_G,S_G),commands(CC_G,V2_G,S_G),h(in_state(V1_G,S_G),T_G),h(in_state(V2_G,S_G),T_G),V1_G!=V2_G,s_gen0(V2_G),s_gen0(V1_G),s_gen3(S_G).
:-next(T_G,T1_G),occurs(flip(Sw_G,gpc),T_G),controls(Sw_G,V_G),not  issued_commands(V_G,T1_G).
issued_commands(V_G,T_G):-commands(CC_G,V_G,S_G),occurs(CC_G,T_G).
:-T2_G>T1_G,controls(Sw_G,V_G),state_of(S_G,v_switch),occurs(flip(Sw_G,gpc),T1_G),occurs(flip(Sw_G,S_G),T2_G),not  command_between(Sw_G,T1_G,T2_G).
command_between(Sw_G,T1_G,T2_G):-T1_G<T_G,T_G<T2_G,controls(Sw_G,V_G),commands(CC_G,V_G,S_G),occurs(CC_G,T_G),s_gen1(T1_G),s_gen1(T2_G).
:-link(N1_G,N2_G,V_G),h(in_state(V_G,open),T_G),not  h(pressurized(N1_G),T_G),not  has_leak(V_G),not  stuck_device(V_G),not  h(in_state(V_G,open),0),s_gen0(V_G).
h(pressurized(N_G),T_G):-tank(TK_G),h(pressurized_by(N_G,TK_G),T_G).
tank(TK_G):-tank_of(TK_G,R_G).
:-controls(Sw_G,V_G),commands(CC_G,V_G,S_G),occurs(CC_G,T_G),not  h(in_state(Sw_G,gpc),T_G),s_gen2(Sw_G).
:-perf(in_state(V_G,open),T_G),prev(V1_G,V_G),not  dummy_valve(V1_G),not  open_prev(V_G,T_G).
:-perf(in_state(V_G,open),T_G),dummy_valve(V1_G),prev(V1_G,V_G),prev(V2_G,V1_G),V1_G!=V2_G,V_G!=V2_G,V1_G!=V_G,not  open_prev(V1_G,T_G).
perf(in_state(V_G,open),T_G):-controls(Sw_G,V_G),occurs(flip(Sw_G,open),T_G).
perf(in_state(V_G,open),T_G):-commands(CC_G,V_G,open),occurs(CC_G,T_G).
prev(V1_G,V2_G):-link(N1_G,N2_G,V1_G),link(N2_G,N3_G,V2_G),N1_G!=N2_G,N2_G!=N3_G,N1_G!=N3_G,V1_G!=V2_G.
open_prev(V_G,T_G):-prev(V1_G,V_G),h(in_state(V1_G,open),T_G),s_gen0(V1_G).
h(pressurized_by(ffh,ffh),0).
h(pressurized_by(foh,foh),0).
h(pressurized_by(lfh,lfh),0).
h(pressurized_by(loh,loh),0).
h(pressurized_by(rfh,rfh),0).
h(pressurized_by(roh,roh),0).
h(in_state(Sw_G,gpc),0):-of_type(Sw_G,v_switch),not  nh(in_state(Sw_G,gpc),0).
h(in_state(V_G,closed),0):-of_type(V_G,valve),not   h(in_state(V_G,open),0).
stuck(V_G,open):-dummy_valve(V_G),s_gen0(V_G).
stuck(rfi345a,closed).
stuck(rfi345b,closed).
goal(T_G,right_rcs):-jet_of(r4d,right_rcs),h(ready_to_fire(r4d),T_G).
done_1(fwd_rcs).
done_1(left_rcs).
s_gen0(lox12).
s_gen0(ffdummy).
s_gen0(ffm1).
s_gen0(ffm2).
s_gen0(ffm3).
s_gen0(ffm4).
s_gen0(ffm5).
s_gen0(rom4).
s_gen0(rom5).
s_gen0(rom2).
s_gen0(rom3).
s_gen0(rom1).
s_gen0(rohb).
s_gen0(roha).
s_gen0(lfhb).
s_gen0(rfhb).
s_gen0(rfha).
s_gen0(lfha).
s_gen0(foha).
s_gen0(fohb).
s_gen0(loi12).
s_gen0(foi345).
s_gen0(ffhb).
s_gen0(ffha).
s_gen0(rfm2).
s_gen0(roi12).
s_gen0(rfm1).
s_gen0(rfm4).
s_gen0(loi345b).
s_gen0(rfm3).
s_gen0(loi345a).
s_gen0(rfm5).
s_gen0(foi12).
s_gen0(rfx12).
s_gen0(rodummy).
s_gen0(lfi12).
s_gen0(lox345).
s_gen0(lfdummy).
s_gen0(rfi12).
s_gen0(lodummy).
s_gen0(rfx345).
s_gen0(fodummy).
s_gen0(rox345).
s_gen0(lfm1).
s_gen0(lfm2).
s_gen0(lfx12).
s_gen0(lom1).
s_gen0(lfx345).
s_gen0(rfdummy).
s_gen0(ffi345).
s_gen0(lom3).
s_gen0(ffi12).
s_gen0(rfi345b).
s_gen0(lom2).
s_gen0(rfi345a).
s_gen0(lom5).
s_gen0(lom4).
s_gen0(roi345a).
s_gen0(lfi345a).
s_gen0(lfi345b).
s_gen0(roi345b).
s_gen0(fom5).
s_gen0(fom4).
s_gen0(lfm5).
s_gen0(fom1).
s_gen0(fom2).
s_gen0(lfm4).
s_gen0(lfm3).
s_gen0(fom3).
s_gen0(lohb).
s_gen0(loha).
s_gen0(rox12).
s_gen1(3).
s_gen1(2).
s_gen1(1).
s_gen1(0).
s_gen1(5).
s_gen1(4).
s_gen2(lx345).
s_gen2(fm4).
s_gen2(rhb).
s_gen2(fm3).
s_gen2(ri345a).
s_gen2(ri345b).
s_gen2(fm5).
s_gen2(fi12).
s_gen2(rha).
s_gen2(fm2).
s_gen2(fm1).
s_gen2(fhb).
s_gen2(ri12).
s_gen2(rx12).
s_gen2(li12).
s_gen2(lha).
s_gen2(lhb).
s_gen2(li345a).
s_gen2(lm4).
s_gen2(li345b).
s_gen2(lm3).
s_gen2(lm2).
s_gen2(lm1).
s_gen2(rm4).
s_gen2(rm3).
s_gen2(lm5).
s_gen2(rm5).
s_gen2(rm2).
s_gen2(rm1).
s_gen2(rx345).
s_gen2(fha).
s_gen2(fi345).
s_gen2(lx12).
s_gen3(open).
s_gen3(closed).
s_gen3(gpc).
s_gen4(open_lfm4).
s_gen4(opena_rfm5).
s_gen4(open_lfm2).
s_gen4(open_lfm3).
s_gen4(closeb_loi12).
s_gen4(open_lfm1).
s_gen4(opena_foi12).
s_gen4(openb_rfm5).
s_gen4(close_lfx12).
s_gen4(open_rfx345).
s_gen4(cc(opena_rfm5,openb_rfm5)).
s_gen4(opena_ffi12).
s_gen4(closeb_foi12).
s_gen4(closea_lfha).
s_gen4(openb_ffm5).
s_gen4(closea_lfhb).
s_gen4(close_lox345).
s_gen4(close_lfi345a).
s_gen4(close_lfi345b).
s_gen4(close_lox12).
s_gen4(opena_rx12).
s_gen4(cc(opena_lfm5,openb_lfm5)).
s_gen4(cc(closea_ri12,closeb_rfi12)).
s_gen4(close_rox345).
s_gen4(closeb_rfm2).
s_gen4(closeb_rfm3).
s_gen4(closeb_lfi12).
s_gen4(closeb_rfm1).
s_gen4(opena_foi345).
s_gen4(closea_rfhb).
s_gen4(open_lfx345).
s_gen4(closea_rfha).
s_gen4(opena_ri12).
s_gen4(closeb_lfm4).
s_gen4(closeb_lfm5).
s_gen4(opena_ffm5).
s_gen4(closeb_lfm2).
s_gen4(closeb_lfm3).
s_gen4(cc(close_rx12,close_rfx12)).
s_gen4(opena_lx12).
s_gen4(closeb_lfm1).
s_gen4(closea_lfm5).
s_gen4(close_lx12).
s_gen4(closea_ri12).
s_gen4(closea_lfm3).
s_gen4(closea_lfm4).
s_gen4(closea_lfm1).
s_gen4(closea_lfm2).
s_gen4(open_loi345b).
s_gen4(open_loi345a).
s_gen4(openb_roi12).
s_gen4(closeb_rfm5).
s_gen4(opena_ffi345).
s_gen4(closeb_rfm4).
s_gen4(cc(closea_fi12,closeb_ffi12)).
s_gen4(closea_ffha).
s_gen4(close_rfi345b).
s_gen4(openb_rfi12).
s_gen4(cc(closea_lfm5,closeb_lfm5)).
s_gen4(cc(closea_fi12,closeb_foi12)).
s_gen4(close_rfi345a).
s_gen4(openb_lfx12).
s_gen4(openb_lox12).
s_gen4(closea_ffhb).
s_gen4(open_roi345a).
s_gen4(cc(closea_ffm5,closeb_ffm5)).
s_gen4(open_roi345b).
s_gen4(closeb_ffi12).
s_gen4(closea_li12).
s_gen4(openb_loi12).
s_gen4(closeb_roi12).
s_gen4(open_rfm4).
s_gen4(closea_ffm4).
s_gen4(close_rox12).
s_gen4(closea_ffm3).
s_gen4(closea_ffm5).
s_gen4(closea_ffm2).
s_gen4(closea_ffm1).
s_gen4(closeb_ffm2).
s_gen4(closeb_ffm3).
s_gen4(closeb_ffm1).
s_gen4(openb_rfx12).
s_gen4(closeb_ffm4).
s_gen4(closeb_ffm5).
s_gen4(open_ffm2).
s_gen4(open_rfm2).
s_gen4(opena_rfhb).
s_gen4(close_rfx12).
s_gen4(open_rfm3).
s_gen4(open_ffm3).
s_gen4(open_rfm1).
s_gen4(opena_rfha).
s_gen4(open_ffm1).
s_gen4(open_ffm4).
s_gen4(opena_li12).
s_gen4(open_rox345).
s_gen4(cc(close_lx12,close_lfx12)).
s_gen4(opena_lfhb).
s_gen4(opena_lfha).
s_gen4(closea_rfm1).
s_gen4(closea_rfm2).
s_gen4(closea_rfm4).
s_gen4(openb_lfi12).
s_gen4(closea_rfm3).
s_gen4(closea_rfm5).
s_gen4(close_loi345b).
s_gen4(close_loi345a).
s_gen4(cc(close_lx12,close_lox12)).
s_gen4(close_rx12).
s_gen4(open_lfi345b).
s_gen4(closea_fi12).
s_gen4(open_lfi345a).
s_gen4(cc(opena_ffm5,openb_ffm5)).
s_gen4(cc(closea_ri12,closeb_roi12)).
s_gen4(cc(closea_li12,closeb_lfi12)).
s_gen4(closeb_rfi12).
s_gen4(opena_lfm5).
s_gen4(close_roi345a).
s_gen4(opena_ffha).
s_gen4(close_roi345b).
s_gen4(close_lfx345).
s_gen4(opena_ffhb).
s_gen4(cc(close_rx12,close_rox12)).
s_gen4(cc(closea_li12,closeb_loi12)).
s_gen4(close_rfx345).
s_gen4(cc(closea_rfm5,closeb_rfm5)).
s_gen4(open_lox345).
s_gen4(openb_rox12).
s_gen4(open_rfi345b).
s_gen4(open_rfi345a).
s_gen4(openb_lfm5).
s_gen5(right_rcs).
s_gen5(fwd_rcs).
s_gen5(left_rcs).
s_gen5(ohms).
