/* Generated By:JJTree: Do not edit this line. QASTterm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=QAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package querying.parsing.query;

public
class QASTterm extends SimpleNode {
  public QASTterm(int id) {
    super(id);
  }
  
  public QASTterm() {
	  this(QueryParserTreeConstants.JJTTERM);
  }
  
  public QASTterm(QueryParser p, int id) {
    super(p, id);
  }
  
  public String toString()
  {
	  return ((SimpleNode)this.jjtGetChild(0)).toString();
  }
  
  public static QASTterm createTermFromVariable(String variableName) {
	  QASTterm term=new QASTterm();
	  QASTvar var= new QASTvar();
	  var.image=variableName;
	  term.jjtAddChild(var, 0);
	  return term;
  }
  
  public boolean isNumericConstant() {
	  String image=this.toString();
	  for (int i=0;i<image.length();i++) {
		  if(i==0 && image.charAt(i)<'1' || image.charAt(i)>'9') {
			  return false;
		  } else {
			  if(image.charAt(i)<'0' || image.charAt(i)>'9')
				  return false;
		  }
	  }
	  return true;
  }

}
/* JavaCC - OriginalChecksum=7f60b93e52ae5079407838efb9dd14dd (do not edit this line) */
