/* Generated By:JJTree: Do not edit this line. QASTvar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=QAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package querying.parsing.query;

public
class QASTvar extends SimpleNode {
  public QASTvar(int id) {
    super(id);
  }

  public QASTvar() {
	  this(QueryParserTreeConstants.JJTVAR);
  }
  public QASTvar(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ee374bd831f8e596125cb817ab78683 (do not edit this line) */
